### ISSUE TITLE
[Brl.Stringbuilder] Add Equals(s:TStringBuilder)

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#145]
StringBuilder for now has no simple way to check if the "content" of the builder is the same.

it is _not_ the same if:
- length differs
- content differs

Checking the length first is for speed reasons.

So I suggest to add a simple `Method Equals(other:TStringBuilder)` (or maybe even an overload `Method Equals(other:String)`.

**Comment by HurryStarfish** [comment]
Wouldn't it be better to give it overloaded `=` and `<>` operators instead?

Perhaps in addition, it could get `<`, `>`, `<=`, `>=` and `Compare`, returning the same results as they would for strings.

**Comment by GWRon** [comment]
This depends on what you expect from "compare" - equality if they are the same instance - or equality of the content.

Also it might be more efficient (in "C") if you want to disable case sensitivity.


Why comparing at all? Brucey proclaimed the StringBuilder as the faster alternative to "string + string + string" - so it should be more efficient to use a `TStringBuilder` for concatenated strings. And I use stringBuilders to store text caches I need to compare often (to invalidate a texture cache of the rendered text).

Also: adding a new function allows an easy backport to "vanilla" (operator overloading not supported there).

**Comment by HurryStarfish** [comment]
> This depends on what you expect from "compare" - equality if they are the same instance - or equality of the content.

Since `=`/`<>` is built into `Object`, it's instance equality by default in lack of a better option. But for something like a string builder it makes sense to compare contents, so imo it should do that. That's what operator overloading is for, after all.

> Brucey proclaimed the StringBuilder as the faster alternative to "string + string + string" - so it should be more efficient to use a TStringBuilder for concatenated strings.

It depends. For many uses, you'll still need to call `.ToString()` in the end, to convert the builder to a `String` once you're done editing it. If you're concatenating less than a certain amount of strings, it's not worth using the builder, since it will be slower than just adding `String` objects. (Depends on the strings - for example with a bunch of strings of length 10, the break-even point seems to be at about a dozen concatenations on my machine.)

> adding a new "classic" function allows an easy backport to "vanilla" (operator overloading not supported there)

That's true, but then again this can be said about a lot of NG's new functionality. Not using those features because vanilla doesn't have them would kinda defeat the point of having them in NG...
Plus, `BRL.StringBuilder` is an NG-specific `BRL` module anyway. (There is a `BaH.StringBuilder` on maxmods which can be used with vanilla.)

**Comment by GWRon** [comment]
I know about bah.stringbuilder ...and in my dig framework I use the predecessor TStringBuffer.

And you are right about the spot until which strings are still the better alternative.

Operator overloading can also take place as it at the end will just call a c-function so we could wrap that in a classic method and... Done.

**Comment by HurryStarfish** [comment]
To elaborate a bit, the reason I'd like to avoid `Equals` methods is because I've seen it "go wrong" in other other languages:

- Java, which lacks operator overloading, requires you to use `==` to compare primitives, but `.equals` for everything else, which is inconsistent and confusing - accidentally comparing objects (especially strings) with `==` is a pretty common mistake.
- C#, uses both `==` overloading and `.Equals` methods, severely overcomplicates things. This is listed as [#9 in this list of most regrettable design decisions](http://www.informit.com/articles/article.aspx?p=2425867), because it's just as confusing and means a lot of unnecessary work for the programmer.

I'd like BlitzMax to avoid these mistakes as far as possible.
When a custom equality comparison between two values makes sense, imo it should work with `=`/`<>`, no matter if it's a `Type` or a `Struct`.
And when a less/greater than comparison makes sense, the `<`/`>`/`<=`/`>=` operators should be implemented as well as `.Compare`, and they should behave consistently with each other.

Object reference equality shouldn't normally matter anymore in these cases. But if ever needed, it's still possible to check for it using `Byte Ptr Object x = Byte Ptr Object y`. Which imo reads quite nicely, since it describes exactly what it does: check whether the two references *point to the same object*.

**Comment by GWRon** [comment]
In the BlitzMax world "a = b" for non-primitive types always means "instance a is the same instance as instance b".
Now changing that behaviour for a single type...can lead to issues too.

I understand your "byte ptr" approach and it could work. But it is not as simple as "a = b".
You do not have to call it "Equals". Maybe call it SameValue() or something else "not so generic". It is just there to allow a fast value comparison


Yet I understand your worries about behaviour consistency and using features NG provides (operator overloading).
For < <= ... It would of course work well like you describe.

**Comment by HurryStarfish** [comment]
> In the BlitzMax world "a = b" for non-primitive types always means "instance a is the same instance as instance b".
> Now changing that behaviour for a single type...can lead to issues too.
> I understand your "byte ptr" approach and it could work. But it is not as simple as "a = b".

How often is there actually a reason to check for instance equality though?
In my experience, one usually simply cares about "equality". For `Type`s, the `=` is pre-implemented as instance equality by default, which can be left as is; or you can overload it, which then replaces the equality you care about.
Wanting to specifically check for instance equality seems fairly rare to me. What code is there that would break by changing `=` of certain types to mean "content equality"?

**Comment by GWRon** [comment]
There does not need to be existing code. For non primitive types the "=" checks instance equality. So TStringBuilder should not be an exception.

**Comment by woollybah** [comment]
Technically, `String` is not a primitive type, and yet it calls String's `Compare` method when you test for equality using `=`.

Since you initiated the issue, you'll now have to take responsibility for any changes to StringBuilder's equality implementation. :-)

**Comment by GWRon** [comment]
I initiated the issue without overloading operators or overriding compare.

You handed responsibility to @HurryStarfish. Hehehe.

**Comment by GWRon** [comment]
I still think ... from a Blitzmax-language-approach POV, that normal NG developers should not need to use `byte ptr A = byte ptr B` to check if two variables A and B are the same.

With overriding the "=" behaviour you now opened a can of worms. Next one asks for a way to check if the pixels of a `TImage` (or pixmap) are the same and you override "=" again.
And so on.


This is why I asked for a custom function.

Now @HurryStarfish is right about the possibility to use `Byte Ptr` for instances-the-same-checks. As said earlier I think this is not usual for BlitzMax codes... and so requiring it should be avoided (or become mandatory for every of these checks... with all the rewrites it needs and all the anger it creates among the users).

**Comment by woollybah** [comment]
> With overriding the "=" behaviour you now opened a can of worms.
No I haven't.

`TStringBuilder` is a "string like" class. It's essentially a `mutable` String. So it doesn't seem unreasonable for the TStringBuilder test `a = b` to act in a similar way to a String `a = b`.

So, now `TStringBuilder` is even more like `String`. This was done both by implementing `Compare()` and overloading `=`. Which is great, isn't it?

> I initiated the issue without overloading operators or overriding compare.

No, you wanted to add some new non-standard method to return a result that could be achieved by using built-in functionality. (or a yet-to-be-implemented `Compare`).
And you think that adding a further method to do something that you should already be able to do using `Compare` would not be confusing to the user?

Anyhoo... it's closed now :-)

**Comment by GWRon** [comment]
I more or less asked for the most efficient c-code-extern-function to compare the string-content of the TStringBuilders. It would have even allowed for additional params (caseSensitivity=False).

Your reason of being a kind of "string" was in my mind too... But still I thought it could somehow create the trouble regarding assumptions of devs.

**Comment by HurryStarfish** [comment]
> I still think ... from a Blitzmax-language-approach POV, that normal NG developers should not need to use byte ptr A = byte ptr B to check if two variables A and B are the same.

Agreed, that's why `a = b` is the "standard" method of comparison.
Perhaps the main point I'm arguing is that nobody normally cares about reference equality, except when there's no other "better" equality check available. Brucey brought up `String` as an example: the `=` operator between strings checks the string contents. Have you ever really needed to check two `String`s for instance equality instead? I don't think I have.
By the way, somewhat similarly, for structs and primitives `=` doesn't necessarily mean "exact" value equality either. For `Float`s for example, `f = -f` returns true when f is `0`, even though `0` and `-0` are technically different values with different bit patterns in memory. Because considering them equal is generally the more useful behaviour when you're working with numbers.

Admittedly, there's a flaw in using `String` as an example like that: `String` is immutable, while `TStringBuilder` is not. In general, I think it's debatable whether `=` on highly mutable types should compare contents or not. For example, on arrays, such a comparison a) could be very expensive and b) would break backwards compatibility, so changing what `=` does between arrays is probably not an option. @GWRon your "comparing the pixels of a pixmap" would be another example - this certainly doesn't seem like a good idea.
But I think in the case of `TStringBuilder`, considering the parallelism with `String`, it makes sense to do this.

**Comment by GWRon** [comment]
@HurryStarfish 
Thanks for your elaborative reply - always a kind of pleasure to read.

I often use the `=` to check if a referenced result is the same than a given param. So I often only compare "memory addresses" instead of actual content.
Also - as you already wrote - this is more likely happening with "highly mutable types" (`if sender = myButtonInstance then ...`).

On the one hand I am completely with you both that it is "natural" to compare content in `if stringBuilderTextA = stringBuilderTextB` but on the other hand I am so used to have an reference/instance equality check there, that it just reads "wrong" (I - and surely other "classic blitzmax users" would interpret it the way that it would return "false" if these variables have the same text but not the same memory address / same "reference").

Maybe stuff will change if you used the `brl.vector` stuff more and more (as you then get used to have operators overridden/overloaded).
Maybe it would be different if `strings` became real objects (with methods) and so you get used to see them "differently" (even if `=` then would be overloaded to compare "content" again).


As said: I like the simplicity this change adds (-> compare content equality with `=`') but I am a bit worried about the discrepance it adds to the language ("is this now an object which compares content or memory reference?  ").

Maybe we should consider adding `==` (hah, and `===` ;-)). :rofl:

**Comment by HurryStarfish** [comment]
> It would have even allowed for additional params (caseSensitivity=False).

That's is a good point, but imo this is a separate issue, because `String`s themselves lack this functionality too, and I think it should be solved for `String` and `TStringBuilder` in the same way. `a.ToLower() = b.ToLower()` (or `a.ToString().ToLower() = b.ToString().ToLower()`) works, but that's neither elegant nor efficient.

Maybe `String` and `TStringBuilder` could both get a method named `CompareIgnoreCase` or `CompareCaseInsensitive` or similar.
Or perhaps: something like `Compare:Int(other:String, comparisonMethod:EStringComparison)`. This would have the advantage of allowing to add other kinds of comparison too. Like ordinal comparison, where "hello15" < "hello123", because 15 < 123.

**Comment by GWRon** [comment]
(I have added an "edit" to my previous post).

@ toLower()
Brucey already prepared a `TLowerString`: https://github.com/GWRon/Dig/blob/master/external/string_comp.bmx
for me (and so also all others). It handles "case insensitive" string comparisons in a way more effective manner.

@ `EStringComparison`
Yes this sounds ... intriguing. Of course people prefer "named functions" so at the end you get your `CompareIgnoreCase()`, `CompareOrdinal()`... and so on too. The parameter-variant allows for a more dynamic and flexible approach.

**Comment by HurryStarfish** [comment]
> Operator overloading might lead to code breaking when backporting to "legacy BlitzMax": you compare some stuff with = in your NG code - now you run the same in legacy BlitMax and behaviour changes. It is not that the code just does not compile (which would be OK) - it compiles but results differ.

But a type that overloads operators wouldn't compile in legacy BlitzMax. This is why I said two posts up that changing `=` for arrays, on the other hand, would be a bad idea.

> Maybe it would be different if strings became real objects (with methods)

[But they are](https://en.wikibooks.org/wiki/BlitzMax/Language/Strings)?

> is this now an object which compares content or memory reference?
> (I - and surely other "classic blitzmax users" would interpret it the way that it would return "false" if these variables have the same text but not the same memory address / same "reference").

Then this is where pointing out `String` makes sense. After all, it shows that even in vanilla, `=` has never meant "reference comparison for everything". And nobody is bothered by this, because intuitively it makes sense for strings to compare contents and not references.
Ultimately, like with `Compare` and any other method, the precise behaviour of `=` for any particular type will be visible in the bbdocs (assuming proper documentation, that is).

**Comment by GWRon** [comment]
> But a type that overloads operators wouldn't compile in legacy BlitzMax.

Wrap it in `?bmxng` and it would - maybe one forgot about the impact it has and adds this conditional and then you created a nice little "bug" (not strictly a bug).


Regarding `TLowerString` I was a bit fast with suggesting it - as the benefit there is the cached "lower string value" which allows for a faster check then. This means in `TStringBuilder` you should then be able to have some flag to set during creation so that every appended text is already converted to lower case.
Not useful for stuff recreated on the fly each time but if you use your `TStringBuilder` to something with a long life then it might become useful.


@ string comparison
It differs the same on assignments (`stringA = stringB` is not creating a reference but a copy).

**Comment by HurryStarfish** [comment]
> Wrap it in ?bmxng and it would - maybe one forgot about the impact it has and adds this conditional and then you created a nice little "bug" (not strictly a bug).

Yes, types that are supposed to be "legacy-compatible" would need to use some legacy-compatible method of comparison. But we are working on NG to eventually make that obsolete, right?

> It differs the same on assignments (`local stringA:string = stringB` is not creating a reference but a copy).

No it doesn't. It just copies the reference, like it does with objects of any other class.

```BlitzMax
SuperStrict
Framework BRL.StandardIO


Local h:String = "hello "
Local w:String = "world"

Local a:String = h + w
Local b:String = h + w

Print "different references:"
Print Size_T Byte Ptr Object a
Print Size_T Byte Ptr Object b
b = a
Print "same reference:"
Print Size_T Byte Ptr Object a
Print Size_T Byte Ptr Object b


Print
Print "a = " + a
Print "b = " + b

Short Ptr (Byte Ptr Object a + SizeOf 0:Int)[0] = Asc("X") ' please never actually do this

Print
Print "a = " + a
Print "b = " + b
```

**Comment by GWRon** [comment]
You are right about strings, dunno why I thought that. My mind seems to mix up stuff at 30°C :-)
Sorry.

@ legacy compatibility
Yes but as long as I (and maybe others) need to use "vanilla" as a backup when there is something bugged (until fixed) in NG I enjoy having modules for both incarnations.
