### ISSUE TITLE
Sockets

### ISSUE THREAD

**Issue by nikikust** [bmx-ng/brl.mod#171]
Hi, can you say, why this program doesn't print remote IP and port of this socket? Thank you
```
Import BRL.Socket

Local socket:TSocket = CreateTCPSocket()
BindSocket(socket, 4444)
SocketListen(socket)
Print("IP: "+SocketRemoteIP(socket)+":"+SocketRemotePort(socket))

CloseSocket(socket)
```

**Comment by DruggedBunny** [comment]
SocketRemote* will only return the IP address of a remotely-connected client, ie. one where your program is the server and a remote client has connected.

It's not possible to get your own client's _public_ IP address without connecting to a third-party server, eg. [http://www.hi-toro.com/ip.php](http://www.hi-toro.com/ip.php) (My site.)

**Comment by GWRon** [comment]
When two clients need to communicate with each other without knowing the IPs of one of them you need a kind of "constant" you could use.

Name lookups for domains allow such stuff. So a dyndns like service can help. Or a webservice running on a webserver you or someone else is hosting.


Also pay attention to ipv4... Newer cable internet connections share a single ipv4 address amongsr hundreds or thousand of other users. You might consider toying around with ipv6 then.

**Comment by nikikust** [comment]
But when i try do this:
`ConnectSocket(socket, AddrInfo(ip, 4444)[0])`
i couldn't connect to server (i started code in top of theme) from another computer with different ip, only by localhost

**Comment by DruggedBunny** [comment]
So it sounds like you have working server code accepting connections, in which case my guess would be firewall, either on the router or the PC running the server code (or both!).

Have you allowed connections through port 4444 in your firewall/s? (Port-forwarding section.)

**Comment by DruggedBunny** [comment]
Oh, that is your server code, sorry. It needs to accept the connection too (SocketAccept).

**Comment by GWRon** [comment]
Is that computer on the same local network? Did you allow network traffic in your firewall (assume you run Windows)?

A local client needs to bind a different local port.

Client1.exe uses 4444 and connects to localip:4445

Server1.exe uses 4445 where it listens to incoming requests.


When using udp instead of TCP you'll not register for a specific port but just use a free one. So targeting the server requires to know what port it would use to listen. For this discovery I mix TCP with UDP (tcp for server discovery and initial hand shakes and udp for network communication then).

**Comment by DruggedBunny** [comment]
Here's a very simple server that should still work.

Before running, note that it waits for a client to send a "QUIT" string before exiting, so you might want to adjust how it works!

```
' Create a TCP socket to handle communications at the server end...

Local server:TSocket = CreateTCPSocket ()

If server

	' Bind the socket to a given port. This means any communications can only
	' happen on this port; port 80 is the standard for HTTP communications --
	' both web browser and web server use this port...
	
	If BindSocket (server, 80)
		
		' Tell the server to listen for incoming connections. The 'backlog'
		' parameter (5 in this case) is best explained in the comments here:
		
		' http://www.blitzbasic.com/codearcs/codearcs.php?code=2482
		
		SocketListen server, 5
		
		' Listen for incoming connections forever...
		
		Repeat
		
			' Check for an incoming connection...
			
			Local client:TSocket = SocketAccept (server)
			
			' If there's no connection, the 'client' socket will be
			' Null. If there is, we can work with it...
			
			If client
			
				' I always check sockets are connected and streams are
				' valid before any read/write operations, as a crash
				' may result if the connection has been lost (or not
				' even set up properly)...
				
				If SocketConnected (client)
					
					' Use Blitz's streams to handle reading/writing over the
					' socket...
					
					Local stream:TStream = CreateSocketStream (client)
					
					If stream
					
						' Keep printing incoming strings until "QUIT" (in capitals)
						' is received...
						
						Repeat
						
							Local incoming:String = ReadLine (stream)
							
							Print incoming
							
						Until incoming = "QUIT"
						
						Exit ' Get out of the enclosing Repeat/Forever loop...
					
					Else
						Print "Failed to create socket stream"
					EndIf
					
				EndIf
				
			EndIf
			
			' Avoid hogging CPU...
		
			Delay 10
			
		Forever
		
	Else
		Print "Couldn't bind to port"
	EndIf
	
	' Close the socket at this end...
	
	CloseSocket server
	
Else
	Print "Couldn't create TCP socket"
EndIf

```

**Comment by nikikust** [comment]
Thanks for answers. But i think that i should ask:
Server:
```
Local socket:TSocket = CreateTCPSocket()
If Not socket StopSocket(socket,,"unable to create socket.") Else Print "socket created"	
If BindSocket(socket, 4444)   Print "socket bind complete"
SocketListen(socket)
Print "socket now listening"
Print("IP: "+SocketRemoteIP(socket)+":"+SocketRemotePort(socket))
Local client:TSocket=socket.Accept()
Print "connected with "+client.RemoteIp()+":"+client.RemotePort()

'Something next
```

Client:
```
Local socket:TSocket = CreateTCPSocket()
If Not socket StopSocket(socket,,"unable to create socket.") ElseIf debug Print "socket created"

'If Not infos StopSocket(socket,,"hostname could not be resolved.")
'Local info:TAddrInfo = infos[0]
	
If Not ConnectSocket(socket, AddrInfo(ip, 4444)[0])
	StopSocket(socket,,"Error connecting to remote")
Else
	If debug Print "Socket connected to "+ip
EndIf

'Something next
```
Will this work with fast connect?

**Comment by woollybah** [comment]
Using your examples (slightly tweaked, as shown)
Server
```blitzmax
SuperStrict

Framework brl.standardio
Import brl.socket

Local socket:TSocket = CreateTCPSocket()
If Not socket Throw "unable to create socket." Else Print "socket created"	
If BindSocket(socket, 4444)   Print "socket bind complete"
SocketListen(socket)
Print "socket now listening"
Print("IP: "+SocketRemoteIP(socket)+":"+SocketRemotePort(socket))
Local client:TSocket=socket.Accept()
Print "connected with "+client.RemoteIp()+":"+client.RemotePort()
socket.Close()
```
Client
```blitzmax
SuperStrict

Framework brl.standardio
Import brl.socket

Local debug:Int = True
Local ip:String = "127.0.0.1"

Local socket:TSocket = CreateTCPSocket()
If Not socket Throw "unable to create socket." ElseIf debug Print "socket created"

'If Not infos StopSocket(socket,,"hostname could not be resolved.")
'Local info:TAddrInfo = infos[0]
	
If Not ConnectSocket(socket, AddrInfo(ip, 4444)[0])
	Throw "Error connecting to remote"
Else
	If debug Print "Socket connected to "+ip
EndIf
```

results in the following output, when both server and client are running on the same Windows machine :
```
Executing:server.exe
socket created
socket bind complete
socket now listening
IP: :0
connected with 127.0.0.1:57629

Process complete
```
and for client (run from command line)
```
socket created
Socket connected to 127.0.0.1
```

**Comment by woollybah** [comment]
> Will this work with fast connect?
What are your trying to do, exactly?

**Comment by nikikust** [comment]
I trying connect from computer, which not in my lan, by my global IP

**Comment by GWRon** [comment]
This most probably requires portforwarding ...and a real public ipv4 address (not a shared one).

Else it might just work with hole punching (depends on the setup of your ISP).

**Comment by nikikust** [comment]
Nice... This means that i need static IP

**Comment by GWRon** [comment]
No it doesn't mean that.

**Comment by GWRon** [comment]
With IPv4 your internet connection was the thing you address/target. So all computers in your LAN had the very same public address. To make a specific computer targetable you need to do port forwarding. Means a specific "public port" is redirected to a "LAN-IP:internal port". Ports can differ.

So "publicIP:80" (80 is the http-port for non-ssl-webserver-stuff) can be port forwarded to "LAN-IP:81" (maybe your LAN-IP:80 is serving a intranet website only available via LAN). But you may also forward to "LAN-IP:80". Port forwarding has to be done in your router (nowadays this is often your "modem")

So far, no problem - if you lived <2005 (or so). Today there are not much IPv4 addresses ("xxx.xxx.xxx.xxx") available anymore. So ISP (your internet service provider) tend to do stuff like "DS-Lite". As not all servers in the internet are compatible with ipv6 (xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx) they have a single IPv4 address which is shared amongst multiple users at the same time. This works as people usually request something from a server - so your ISP knows from where the original package was sent when a server returns its reply. It's kind of a "hole punching" approach (to punch through firewalls - which allow incoming data once there was outgoing data to the remote address).
If you have "Dual Stack" (not Dual Stack Lite) you have both: a valid ipv4 and ipv6. So port forwarding is an option for you.

But if you have only a valid ipv6 then you need:
- tunnel your remote via some services (they relay the communication via their web servers) so that the remote computer becomes part of your LAN
- handle stuff via IPv6 (does not need port forwarding because now each computer is directly accessible via its unique IPv6 address worldwide)

**Comment by nikikust** [comment]
i have only ipv4. Ok, thank you for your answers, now is late then i will work with this tomorrow.

**Comment by woollybah** [comment]
If you want access to the remote ip that has connected to the server you can pass in a `TSockaddrStorage` object as the second parameter of `Accept`. This will be populated when the client connects to the server. From that you can call `Address()` to retrieve the IP Address.

**Comment by woollybah** [comment]
If you want to connect **from** the internet to a computer **inside** your local network, you can have your router forward the request from outside to the specific computer on your network, or more commonly - where games are concerned - your internal server is registered to some third-party server that is on the internet, which is waiting for connections from clients, and will connect the two ends of the connection via it.

**Comment by nikikust** [comment]
I think that your last comment is closest to my answer: "how to connect to server.bmx with client.bmx from another computer which doesn't in server lan".

**Comment by nikikust** [comment]
One question more, client need readdressing too?

**Comment by nikikust** [comment]
It's very problematic... I didn't found any normal info for this situation about sockets and BM.

**Comment by GWRon** [comment]
We already gave all answers you should need. If you have more questions...ask them but make sure they are understandable and contain necessary details.

**Comment by nikikust** [comment]
Ok, i did normal connection. I've figured out what sockets can do, and now I finally understand what you wanted to tell me. Thanks to all
