### ISSUE TITLE
WParam and LParam

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/brl.mod#38]
Hiya, 

I'm just curious as to why you've made wparam and lparam as a built-in type?

**Comment by woollybah** [comment]
Because I didn't come up with any better ideas :-p

Byte Ptr wasn't working properly...
I needed types that changed size depending on architecture, one for Int/Long and one for UInt/ULong.
SizeT does that for unsigned, but I thought that would just add confusion.

The other option was to change the code to use Int or Long (and UInt or ULong) depending on architecture - which would have required populating the code with ?ptr64 / ?not ptr64 everywhere.

In the end, the code stays reasonably clean :
```blitzmax
Function ClassWndProc:Byte Ptr(hwnd:Byte Ptr,msg:UInt,wp:WParam,lp:LParam) "win32"
```
and should in theory require less effort maintaining it.
The compiler option way would have looked like this :
```blitzmax
?ptr64
Function ClassWndProc:Byte Ptr(hwnd:Byte Ptr,msg:UInt,wp:ULong,lp:Long) "win32"
?not ptr64
Function ClassWndProc:Byte Ptr(hwnd:Byte Ptr,msg:UInt,wp:UInt,lp:Int) "win32"
?
```
as well as fixing all calls to them.

So, I dunno :-)

What's your "plan b" ?

**Comment by davecamp** [comment]
ahh ok, I didn't know there was an issue with using them as pointers.

SizeT is unsigned, how about SSize_T for its signed partner?

**Comment by davecamp** [comment]
Or you don't want to use Size_T, SSize_T at all, due to possible confusion?
Also is it only windows that you're looking solutions for?

**Comment by woollybah** [comment]
> I didn't know there was an issue with using them as pointers.

Yeah.. having done the migration to param types, MaxIDE (at least) appears to function more correctly now. Perhaps there were issues in places when casting to/from Byte Ptr.

Size_t is Size_t. If I start using it as an argument for some other datatype it *feels* like it will just confuse.

And yes, this is a Windows-only solution. You should get an error trying to compile param types on the other platforms... much in the same way that intrinsics is only available on x64.

I imagine 99% of users wouldn't even notice, as they only tend to be used directly in Win32 API calls.

**Comment by davecamp** [comment]
I can see your reasoning, and yeah I understand the possible confusion of size_t, especially in that scenario.
I just have a niggly itch about using windows only types as built in types - ie they're not language types but windows defined, oh well I guess they are windows only after all.

Maybe the issue is elsewhere?

hmm..... thinking....
