### ISSUE TITLE
possible bug in GC?

### ISSUE THREAD

**Issue by davecamp** [bmx-ng/brl.mod#63]
Hiya,

A user over at syntaxbomb may have discovered a rather obscure bug. It would be better to point you to the conversation thread so that you could follow it for a bigger picture of the situation.

https://www.syntaxbomb.com/index.php/topic,4327.0.html

**Comment by woollybah** [comment]
Hi, thanks.
The issue is that ```DeleteTex()``` is called from ```TGLImageFrame.Delete()```. which isn't so bad in itself, but because there's ```dead_texs=dead_texs[..n_dead_texs+10]``` that may invoke another GC cleanup, which in turn can result in freeing an image frame.

A dirty "fix" is to change the "+10" to something larger, like 256, which just makes it less likely to reach end of the array.

I seem to have already done that in SDL's gl2sdlmax2d.

A better fix would be to not invoke the GC again whilst collecting...

**Comment by woollybah** [comment]
Heh, the comment above the function kind of implies that it's just a problem just waiting to be found...
```blitzmax
'Enqueues a texture for deletion, to prevent release textures on wrong thread.
'
'Not thread safe, but that's OK because all threads are stopped when TGLImageFrame.Delete()
'is called, which is what calls us.
```

**Comment by woollybah** [comment]
I've had a stab at doing the array mod stuff during tex creation instead.

Let me know if that seems to work better.

Thanks!

**Comment by davecamp** [comment]
'Morning,
The fix seems to work ok for me using that users test code.
:+1:

**Comment by woollybah** [comment]
I'll probably make some more changes to prevent races on ```n_dead_texs```, since the GC is multi-threaded.
