### ISSUE TITLE
Fullscreen Max2D on Mac leads to inverted MouseY()

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#79]
According to a report on syntaxbomb:
https://www.syntaxbomb.com/index.php/topic,4951.msg21354.html#msg21354
(and follow-up posts) a user has issues on Mojave when running NG apps in fullscreen.

Windowed mode has correct mouseY() results while in fullscreen the coordinates are inverted.

Maybe it is an OpenGL issue (opengl viewports start 0,0 at bottom left) ?

Can one Mac user (on Mojave...) verify this issue?

**Comment by mickmuze** [comment]
I’m the user that has been having the problem with MouseY() being inverted on full screen. I just thought I would post example code here in hopes someone will verify the issue on a Mac with the latest Mojave.

 `Global MouseIcon:TImage
MouseIcon = LoadImage("10x10icon.png")

DrawCursor()

Function DrawCursor()
	
		Repeat
			Cls
			DrawImage(MouseIcon,MouseX(), MouseY())
			DrawText(MouseY()),10,10
			If KeyDown(KEY_ESCAPE) Then End
			Flip
		Forever
		
End Function`

**Comment by woollybah** [comment]
Hi. There are several issues currently with Mojave and the default OpenGL graphics modules for BlitzMax.

I would like to suggest moving over to use the SDL backend (sdl.mod) on macOS. The latest SDL has fixed all the currently known macOS issues (fullscreen y flipping, fullscreen refresh sync, etc), and their team is generally quick to fix new ones.

Generally, all you need to do is to import `SDL.gl2sdlmax2d`, rather than `BRL.GLMax2D`.
If you are not using a `Framework` (and therefore all of BRL and Pub modules are automatically imported) you will need to switch to using the `Framework` statement, and then import the required modules for your project.

**Comment by mickmuze** [comment]
Thank you! :)

Most of this stuff is over my head. I did manage to download the SDL backend. Never used Framework before, but with some fiddling around and trial and error, I managed to figure out which mods I needed to import to get this thing running correctly again. 

When compiling, I got a few of these errors: "libpng warning: iCCP: known incorrect sRGB profile" ... But other than that, everything seems to be running fine and smooth again.

**Comment by GWRon** [comment]
Libpng... Save the corresponding PNG files with an other image editor.

**Comment by mickmuze** [comment]
👍🏻

**Comment by sphinxeg** [comment]
> According to a report on syntaxbomb:
> https://www.syntaxbomb.com/index.php/topic,4951.msg21354.html#msg21354
> (and follow-up posts) a user has issues on Mojave when running NG apps in fullscreen.
> 
> Windowed mode has correct mouseY() results while in fullscreen the coordinates are inverted.
> 
> Maybe it is an OpenGL issue (opengl viewports start 0,0 at bottom left) ?
> 
> Can one Mac user (on Mojave...) verify this issue?

I confirm this on Mojave 10.14.3

**Comment by woollybah** [comment]
Re my above note about using the SDL backend on macOS to resolve most of the current rendering/mouse issues.

**Comment by GWRon** [comment]
@woollybah 
Maybe add a "warning" message for glmax2d on mac Mojave?
