### ISSUE TITLE
Bmx NG fail to compile brl.appstub on opensuse 13.2

### ISSUE THREAD

**Issue by olejr** [bmx-ng/brl.mod#8]
bmk makemods -g x86 
Compilng: debugger_mt.stdio.bmx
Compile Error: Missing function argument 'message'
[/home/olejr/bmx-ng/mod/brl.mod/appstub.mod/debugger_mt.stdio.bmx;384;0]

bmk -v
bmk 2.24 linux-x86 / gcc 040803

**Comment by GWRon** [comment]
Did you try bmk 2.25 ? Contains a fix regarding NG detection.

**Comment by olejr** [comment]
Same thing..

And seem strange to me that I should get this error, when you guys probably have rebuilt the modules
many times over..

**Comment by GWRon** [comment]
It has to do with changes regarding function pointers. It is not an issue with the module, but with the compiler.

In short: the line having issues is a "functionPointerVariable = function" line. The compiler somehow things, you want to store the result of "function" in this pointer (because it is an "int" too). Therefore it wants to see the params of "function" too.

Have opened an issue in the bcc-section.

**Comment by olejr** [comment]
Ok. thanks!

**Comment by woollybah** [comment]
This should be fixed with v 0.46 of bcc.
